### ISSUE TITLE
Javascript error in SE on attempting to launch 

### ISSUE THREAD

**Issue by ferdf56** [SkyrimTogether/issues-launcher#83]
## Steps to reproduce

How to reproduce this issue:

1. Start the launcher.
2. Connect login.
3. Fail to login.

## Reproduction rate

How many times can you reproduce it?

## Expected result

Describe your expected result.

## Your environment

* Launcher version:

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition

* Operating system (choose one):
    * Windows 7 x32
    * Windows 7 x64
    * Windows 10 x32
    * Windows 10 x64

## Evidence (optional)

Show us what happen.

## Final checks for the reporter

- [ ] I have browsed through the other issues and confirmed that this issue has not been reported already
- [ ] I made sure that I have applied the template for my bug report

**Comment by oxxxman** [comment]
i get the same issue when i try to launch 
![Harbor Error](https://user-images.githubusercontent.com/16161265/99145061-75174380-26bf-11eb-8908-4b5b60471b6c.png)

**Comment by JakyWolfBoi2021** [comment]
Me too

**Comment by JakyWolfBoi2021** [comment]
I do too it all started after I had an update for Harbor...
I AM REALLY SAD T_T

**Comment by JakyWolfBoi2021** [comment]
It says Uncaught Exception:
Error: spawn UNKNOWN
at ChildProcess.spawn(interal/child_process.js:358:11)
at Object .spawn(Child_process.js:543:9)

There seems to be something to do with Whatever Child_process.js:###:#

And Harbor\recurces\app.asar\app.js:###:#####
And where ever the harbor.exe is. Also it mentions Tilted Phoques...
This is all I know

**Comment by JakyWolfBoi2021** [comment]
https://www.reddit.com/r/SkyrimTogether/comments/cgdrda/java_script_error_while_launching_skyrim_together/eugywco/?utm_source=share&utm_medium=web2x
Check out this link it should help
